### ISSUE TITLE
Caouecs\Laravel-Lang v3 : new directory for languages files

### ISSUE THREAD

**Issue by caouecs** [ablunier/laravel-lang-installer#2]
Hello,
with the v3 ( see: https://github.com/caouecs/Laravel-lang/issues/531 ) we have changed the directory for languages files.

**Comment by addow** [comment]
This issue should be fixed in #3 as well as compatibility with Laravel 5.x.
I took the time to fix the installer, merely because Fred suggests this package when you install the [caouecs/Laravel-lang](https://www.github.com/caouecs/Laravel-lang) package.

**Comment by ablunier** [comment]
Thanks @addow for taking the time to fix this. PR tested and merged. Appreciate!

**Comment by addow** [comment]
Great! Anytime. By the way, are you planning a new version release soon to make it available through packagist?

**Comment by ablunier** [comment]
Yes, done: https://github.com/ablunier/laravel-lang-installer/releases/tag/1.1.0
